<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>a_Uncategorized</name>
   <tag></tag>
   <elementGuidId>323b41d5-d4ea-4c4d-95a1-d4f58e63d6ae</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>li.cat-item.cat-item-15 > a.site-secondary-font</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//main[@id='main']/div/div/div/aside/aside/ul/li[3]/a</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>a69625d9-58a1-4f27-85a2-bdeafaa337ee</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>site-secondary-font</value>
      <webElementGuid>c1cec779-6bc2-4c1d-8306-2841bbc99c08</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>href</name>
      <type>Main</type>
      <value>https://kotakoki.wijaysali.my.id/product-category/uncategorized/</value>
      <webElementGuid>1609dcb1-62d2-46a8-a2f7-aef4d9859ee5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Uncategorized</value>
      <webElementGuid>8ee2ea8f-a776-4cc3-a864-5f7b05c574fd</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;main&quot;)/div[@class=&quot;row&quot;]/div[@class=&quot;small-12 large-3 columns show-for-large&quot;]/div[@class=&quot;woocommerce-sidebar-sticky&quot;]/aside[@class=&quot;site-sidebar site-sidebar--shop widget-area&quot;]/aside[@class=&quot;widget woocommerce widget_product_categories_with_icon&quot;]/ul[@class=&quot;product-categories-with-icon&quot;]/li[@class=&quot;cat-item cat-item-15&quot;]/a[@class=&quot;site-secondary-font&quot;]</value>
      <webElementGuid>f864928a-e3dc-4d7e-ad8d-36377bef5fb8</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//main[@id='main']/div/div/div/aside/aside/ul/li[3]/a</value>
      <webElementGuid>b08e5ebf-246c-40c5-b79a-835f75af6f30</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:link</name>
      <type>Main</type>
      <value>//a[contains(text(),'Uncategorized')]</value>
      <webElementGuid>0a3a5501-cbd8-42b0-b5c9-bf4d4050d6d9</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Cocoqua ココナッツ'])[2]/preceding::a[1]</value>
      <webElementGuid>3c94de44-80ef-4846-99d0-97b6ec0042d3</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Du-reamyドリアン'])[2]/preceding::a[2]</value>
      <webElementGuid>2600cbd0-ec87-4604-b5ae-bf8bbb7a7ec5</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:href</name>
      <type>Main</type>
      <value>//a[contains(@href, 'https://kotakoki.wijaysali.my.id/product-category/uncategorized/')]</value>
      <webElementGuid>4d9a8b3c-1b8d-4033-9d5b-50510c5a297a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//aside/ul/li[3]/a</value>
      <webElementGuid>e1f93766-6e8d-4f79-ba07-f8aeef3080f2</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//a[@href = 'https://kotakoki.wijaysali.my.id/product-category/uncategorized/' and (text() = 'Uncategorized' or . = 'Uncategorized')]</value>
      <webElementGuid>6dcc2c6a-3cdf-4672-868a-ad907aaa52e0</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
