<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_(optional)_billing_address_2</name>
   <tag></tag>
   <elementGuidId>4aec62e1-c605-4c74-a7ed-224ee33360f5</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#billing_address_2</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='billing_address_2']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>4ea120c9-261f-4420-9b76-89e3a94cbc90</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>f3a3fbd9-f531-4020-a242-c7af5c6b69f4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>input-text </value>
      <webElementGuid>94e040d9-81a6-4b58-9d26-dc55fa16c2af</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>billing_address_2</value>
      <webElementGuid>2e36b0d7-065b-4d82-8037-3ab02d53cd93</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>billing_address_2</value>
      <webElementGuid>11238557-83ff-4f41-9c25-73a7a6b388fa</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>Apartment, suite, unit, etc. (optional)</value>
      <webElementGuid>752e9403-d97f-4638-8b41-3ab99586a01d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>autocomplete</name>
      <type>Main</type>
      <value>address-line2</value>
      <webElementGuid>531c98ec-6954-4a02-87bb-40da624cbdd6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-placeholder</name>
      <type>Main</type>
      <value>Apartment, suite, unit, etc. (optional)</value>
      <webElementGuid>9307f222-caae-4ebe-b261-d37fce564378</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;billing_address_2&quot;)</value>
      <webElementGuid>b23c1117-fc23-496f-a601-8b4b6bf3e374</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='billing_address_2']</value>
      <webElementGuid>c68d6541-6e7c-41ff-ac42-bacec930f744</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//p[@id='billing_address_2_field']/span/input</value>
      <webElementGuid>f745d641-75f3-4ae0-bde6-b86c8ca4e2b7</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//p[6]/span/input</value>
      <webElementGuid>0e4bedaf-bdf3-4f0f-8253-cf0a5a8b3b27</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'text' and @name = 'billing_address_2' and @id = 'billing_address_2' and @placeholder = 'Apartment, suite, unit, etc. (optional)']</value>
      <webElementGuid>82b9fa6a-c943-4a4c-bb60-48194e1d01e5</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
